Fix 161 scroll up
RooftopAcademy/roofstore pull request #178
Opened 2021-12-14 23:30 UTC by pablocanale

# SCROLL TO TOP 

## Issue: #161 

## :memo: Description:

On page changing scroll moves up to top of the page

## :camera: Screenshots:

https://user-images.githubusercontent.com/70720691/146095765-c154aee8-4238-4d7c-a864-b21c00f9addc.mp4

2021-12-15 00:11 UTC, kevin-dev71 requested changes
una de las reglas de los hooks personalizados, es que el nombre del hook debe debe empezar por "use" [documentacion](https://es.reactjs.org/docs/hooks-custom.html)... asi que el archivo `scrollTop.js` deberia retornar una función que se llame `useScrollToTop`  o renombrar el archivo a `useScrollToTop.js`

lo otro que me chilla un poco (desconozco no estoy seguro) es que en vez de ser un hook, preferiría usar un [HOC](https://dev.to/nibble/higher-order-components-in-react-4c7h)... así wrapeamos toda la App con la funcionalidad de scrollToTop y creo que quedaria más legible.

con HOC quedaria asi:

```js
// App.js 
<ScrollTop>
  <Routes>
       /* Routes */
  </Routes>
</ScrollTop>
```

```js
// scrollTop.js

import { useLocation } from 'react-router-dom';
import { useEffect } from 'react';

function ScrollTop({children}) {
    const { pathname } = useLocation();

    useEffect(() => {
        window.scrollTo(0, 0);
    }, [pathname]);

    return children;
}

export default ScrollTop;

```

igual, creo que deberiamos pedir code review a todos aquí, no estoy seguro de cómo sería lo mejor...

2021-12-15 13:33 UTC, Alonso-Pablo commented
Este PR estaba apuntando al `main` 😮‍💨

2021-12-16 12:55 UTC, Alonso-Pablo requested changes

2021-12-16 12:55 UTC, Alonso-Pablo commented on src/App.js
> +          <Route path="/officialStores" element={<OfficialStores />} />
Esto es viejo. La ruta se cambió recientemente a `/store`
Hace un `git pull origin dev`

2021-12-17 01:21 UTC, pablocanale commented on src/App.js
> +          <Route path="/officialStores" element={<OfficialStores />} />
Solucionado, actualizado de la rama dev!

2021-12-17 12:16 UTC, Alonso-Pablo approved these changes

2021-12-17 17:46 UTC, kevin-dev71 approved these changes
✔️ Me gusta

2021-12-17 19:47 UTC, merged